### ISSUE TITLE
SD card speed test doesn't work on Pi 1

### ISSUE THREAD

**Issue by andrum99** [raspberrypi-ui/agnostics#4] opened 2020-03-28 13:20 UTC
The SD card speed test in agnostics doesn't work on the first generation Raspberry Pi devices, aka Pi 1. I've tried 256MB and 512MB variants and both have issues.

Steps to reproduce:

1. Start up agnostics from the menu within the Raspbian desktop.
2. With the "SD Card Speed Test" test selected (which it is by default), press the "run test" button.

Expected output:

Progress dialog appears while test runs, then main window displays PASS or FAIL.

Actual output:

Progress dialog appears briefly, then main window displays "Not Run" in the result column. On the Pi with 256MB, after a delay of a few seconds, the mouse pointer becomes sluggish for a few seconds, then goes back to normal. On the Pi with 512MB, after a similar delay, the mouse pointer becomes sluggish for a few seconds, then stops. The Pi becomes completely unresponsive, although it does still appear to be responding to pings over the network.

I tested on both Pis with the same SD card - a micro SD card in the adapter it came with. This SD card is know to be working fine and had previously been used on a Pi 4B 4GB without issue. The card was imaged with the latest version of Raspbian, and brought fully up-to-date using apt, rebooted, then agnostics was installed using apt. The same OS image was used to test both Pis.

I expect the Pi Zero is also affected, but I don't have a spare one to test this on.

Log file from Pi with 256MB:

> Raspberry Pi Diagnostics - version 0.2
> Sat Mar 28 13:09:45 2020
> 
> Test : SD Card Speed Test
> Run 1
> fio: job startup hung? exiting.
> fio: 1 job failed to start
> Test FAIL

It looks like fio is having trouble for some reason.

Other users have also reported this issue on the forums - see thread at https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=268397

**Comment by spl237** [comment] 2020-03-28 14:19
Interesting - one for Jon to investigate. I'm not sure what his GitHub handle is, so I'll email the report to him. At a guess, fio needs more memory than a Pi 1 has.

**Comment by andrum99** [comment] 2020-05-03 09:41
Now working on 256MB Pi 1 as of agnostics v0.3, but there is a UI glitch: when you press the "test" button, it comes up with the progress dialog, the after about 3 or 4 seconds the progress dialog closes returning focus to the main window, and the result is listed as "not run". However, the test is actually running in the background. Eventually the test completes and the result changes to a red "FAIL" as expected.

Interestingly, the card I used is actually borderline on this Pi 1 (passes with fliying colours on a Pi 4B):

`Raspberry Pi Diagnostics - version 0.3
Sun May  3 10:35:05 2020

Test : SD Card Speed Test
Run 1
prepare-file;0;0;12867;25
seq-write;0;0;7761;15
rand-4k-write;0;0;3085;771
rand-4k-read;6086;1521;0;0
Sequential write speed 7761 KB/sec (target 10000) - FAIL
Note that sequential write speed declines over time as a card is used - your card may require reformatting
Random write speed 771 IOPS (target 500) - PASS
Random read speed 1521 IOPS (target 1500) - PASS
Run 2
prepare-file;0;0;20518;40
seq-write;0;0;16545;32
rand-4k-write;0;0;1668;417
rand-4k-read;5073;1268;0;0
Sequential write speed 16545 KB/sec (target 10000) - PASS
Random write speed 417 IOPS (target 500) - FAIL
Random read speed 1268 IOPS (target 1500) - FAIL
Run 3
prepare-file;0;0;8797;17
seq-write;0;0;10477;20
rand-4k-write;0;0;2424;606
rand-4k-read;5400;1350;0;0
Sequential write speed 10477 KB/sec (target 10000) - PASS
Random write speed 606 IOPS (target 500) - PASS
Random read speed 1350 IOPS (target 1500) - FAIL
Test FAIL

`

**Comment by andrum99** [comment] 2020-05-03 09:48
Confirmed working on Pi 1B 512MB with same UI glitch.

**Comment by andrum99** [comment] 2020-05-03 16:57
Note: I've seen the same UI glitch on faster Pis, but on those it is intermitted. On Pi 1 it happens every time. I'm guessing it is some sort of timing issue.

**Comment by spl237** [comment] 2020-05-03 17:26
Looking at the code, my guess is that the wait call which ought to be waiting for the test process to end is detecting the end of a different child process and falling out early. No idea what child process it is detecting the end of, mind...

I suspect I can fix it by checking the PID of the wait process; I'll give that a go. If I create a test build, can I send it to you for testing?

**Comment by andrum99** [comment] 2020-05-03 18:33
> Looking at the code, my guess is that the wait call which ought to be waiting for the test process to end is detecting the end of a different child process and falling out early. No idea what child process it is detecting the end of, mind...
> 
> I suspect I can fix it by checking the PID of the wait process; I'll give that a go. If I create a test build, can I send it to you for testing?

Yes, no problem.

**Comment by spl237** [comment] 2020-05-04 19:42
The deb file is here - https://www.sendspace.com/file/0puni4

"sudo dpkg -i agnostics_0.4_armhf.deb" to install it.

Many thanks!

**Comment by andrum99** [comment] 2020-05-04 21:15
Using a 512MB Pi 1, I see the same issue on the first run. Progress dialog quits before the progress indicator starts up. I checked with `ps aux | grep fio` and at first it shows a single fio process, checked a couple of seconds later and there's two of them with the exact same command line. Once fio completes, log shows result from a single run of fio, in this case a PASS.

Pressed reset.

Second run: progress dialog comes up and progress indicator starts moving. dialog stays up. Checked processes - 2 of fio. Test completes correctly - progress dialog only exits once test complete. Result - FAIL. (random read fail, other 2 OK).

Pressed reset.

Third run: Progress dialog comes up, with progress indicator in same place as when it closed after the second run, then closes again. fio x 2 left running in the background. PASS

Exited agnostics, went back in again. First run shows progress dialog correctly - only closes once fio finishes. again I have 2 fio processes.

apt purged agnostics 0.4 and installed version 0.3.

First run, progress dialog works correctly. I see a single fio process.

Second run, progress dialog closes early, leaving singe fio running in background.

**Comment by spl237** [comment] 2020-05-05 06:32
OK, thank you very much for testing that - I can see the spurious fio processes happening here as well. I've no idea what is causing them, but I suspect it is some nasty interaction between the multiple threads in the host program and fork/exec.

I'll rewrite the test launcher with a single thread and using the Glib spawn routines and see if that helps - that has ended up being more reliable in similar circumstances elsewhere. Give me a day or so...

**Comment by spl237** [comment] 2020-05-05 09:07
OK, it's not the UI that's causing the problem...

fio itself (which is the underlying test app) spawns multiple instances of itself; as it is simulating I/O, I guess it creates an input process and an output process. This is the reason you see multiple fio processes in ps with the same command line.

The problem is that in order to close everything down properly when the user hits cancel or a test ends, I monitor all the process IDs in the group created when I spawn the shell to run the tests, and this includes the child processes that fio creates itself. So sometimes the ending of one of the child processes is detected (it's odd that it isn't *always* detected, but that's another issue...) and causes the test UI to terminate thinking that fio itself is finished.

I'm now trying to work out what on earth I do about that; I need to find some way of only treating the top level fio process as the one whose termination I need to detect.

But I do at least now understand the problem, by which I was somewhat baffled before!

**Comment by spl237** [comment] 2020-05-05 13:09
No, I didn't understand the problem - it was much simpler than that! ;)

Turned out it was a simple race condition. On Pi 1, it took so long to read the name of the test from the data store that the dialog box update (which happens once a second) occurred first, and as there was no test name available, the dialog box was cleared, leaving the test running in the background.

I've added a flag to get around this problem, and it now works fine on a Pi 1 for me; this will be in the next release.

**Closed by spl237** 2020-05-05 13:09 UTC

**Comment by andrum99** [comment] 2020-05-12 15:00
I've checked this on my Pi 1s and it is now working correctly. One minor issue I've spotted that is still outstanding is that if the test completes and you then press 'reset' and run it again, the progress dialog start off with the text 'running SD card speed test...', then says 'running tests...', then back to 'running SD card speed test...'. It seems to be retaining the text and the progress indicator position from the previous run. This isn't a problem right now, since there is only one test, but in the future if/when another test is added, you will potentially end up with the dialog briefly displaying the wrong message. Shall I file a separate issue for this?

**Comment by spl237** [comment] 2020-05-12 15:44
Is that on a Pi 1 again? I suspect it won't happen on a faster Pi, due to it being a symptom of the same slow access to the data structures that was causing the original problem.

I wouldn't consider it a major problem unless it happens on the more recent Pis, to be honest.

**Comment by andrum99** [comment] 2020-05-12 15:56
> Is that on a Pi 1 again? I suspect it won't happen on a faster Pi, due to it being a symptom of the same slow access to the data structures that was causing the original problem.
> 
> I wouldn't consider it a major problem unless it happens on the more recent Pis, to be honest.

Sorry - yes Pi 1. I tested on a Pi 2 and couldn't get it to do it in that, but it may be present on the Zero, which is a current product still on sale. I don't have a zero to test it on.
